title: Yoda's House
email: yoda@force.com
description: Very good my site is!
baseurl: /
url: https://lucamaina.github.io
twitter_username: yoda
github_username:  yoda

# Build settings
theme: jekyll-theme-cayman
layout: default

permalink: /:year/:month/:day/:title:output_ext