---
title:  Giulia Tesi
date:   2021-09-21
---




Università degli Studi di Torino
Dipartimento di Culture, Politica e Società
Corso di laurea in Comunicazione Interculturale




# Analisi degli effetti dell’esperienza Erasmus nel contesto italiano di transizione all’età adulta






Candidato: Giulia Butera  



Relatore: prof.ssa Raffaella Ferrero Camoletto                                             
                                                                             






Anno accademico: 2020/2021
## INDICE

- Introduzione		
- 1 	La transizione all’età adulta	
- 1.1.	Il concetto di giovane: precisazioni terminologiche	
- 1.2.	Excursus storico sul processo di transizione ai ruoli adulti	
- 1.2.1.	Il mondo greco e romano	
- 1.2.2.	Essere giovani nel Medioevo	
- 1.2.3.	La giovinezza nell’Europa preindustriale	
- 1.2.4.	Ottocento e Novecento	
- 1.2.5.	I giovani del Terzo millennio: cambiamenti e tendenze recenti	
- 1.3.	Il peculiare caso italiano	
- 1.3.1.	La tendenza alla “famiglia lunga”: definizione e cause	
- 1.3.2.	Nuovi stili di avvicinamento all’età adulta	

- 2		Il Progetto Erasmus	
- 2.1.	Storia e definizione del Progetto Erasmus	
- 2.2.	Caratteristiche ed obiettivi	
- 2.3.	Esperienze e percezioni degli erasmiani	

- 3 	Il caso di studio	
- 3.1.	Definizione del progetto di ricerca	
- 3.1.1.	Domanda di ricerca e obiettivi	
- 3.1.2.	Il disegno della ricerca: tecniche e metodologie	
- 3.1.3.	La traccia d’intervista	
- 3.1.4.	Criteri di selezione del campione	

- 4		Analisi dei risultati 
- 4.1.	L’analisi dei risultati
- 4.1.1.	L’Erasmus come esperienza di libertà 
- 4.1.2.	L’Erasmus come periodo di autonomia 
- 4.1.3.	L’Erasmus come esperienza potenzialmente adultizzante 
- 4.1.4.	L’analisi delle variabili: genere, provenienza, situazione abitativa 

- Conclusioni 

Bibliografia 



## INTRODUZIONE


Il nesso che il presente elaborato si pone di indagare è l’interazione tra tre dimensioni: giovinezza, esperienza Erasmus, autonomia. Tre dimensioni apparentemente inconciliabili ma tra cui si cercherà di tracciare un filo rosso volto a scovare connessioni nascoste. 
Il materiale alla base della ricerca di collegamenti saranno racconti e narrazioni di giovani studenti che hanno preso parte al Progetto Erasmus, entrambi protagonisti principali dell’elaborato. 
Il Capitolo 1 offrirà la possibilità di compiere un viaggio nel corso dei secoli, dal mondo greco e romano, al periodo medievale e preindustriale, per giungere dal Novecento fino ai giorni nostri, con l’obiettivo di ricostruire la storia dei giovani, indagandone tendenze e significati. Quali sono state le rappresentazioni prevalenti dei giovani nel corso della storia? Che cosa significa essere giovane? 
Il Capitolo 2 consentirà di ripercorrere dal punto di vista storico l’iter istituzionale che ha condotto all’approvazione del Programma Erasmus nel 1987, di cui verranno presentati i tratti e gli obiettivi principali, oltre alle esperienze di studenti erasmiani narrate attraverso i risultati di studi sociologici. 
Ma sarà solo nei Capitoli 3 e 4 che cominceranno a disvelarsi gli arcani nessi tra giovani, Erasmus e autonomia. I due capitoli sono il punto di congiunzione tra i temi principali delle prime due sezioni, che si incontreranno per dar vita a una ricerca empirica che consiste nella raccolta delle narrazioni di esperienze Erasmus vissute in prima persona dagli studenti. 
Attraverso l’analisi di queste narrazioni si cercherà di indagare il ruolo dell’Erasmus come esperienza potenzialmente adultizzante, dunque come strumento in grado di favorire l’acquisizione dell’autonomia, componente fondamentale nel percorso di transizione ai ruoli adulti. La risposta a questo interrogativo si cercherà avendo come riferimento il contesto italiano, caratterizzato da un modello di transizione peculiare che si traduce in tendenze tipiche come la cosiddetta famiglia lunga, che spinge i giovani italiani a permanere più a lungo all’interno della famiglia d’origine. 
Dunque, le tre dimensioni al centro dell’elaborato sembrano ricomporsi e conciliarsi all’interno dell’interrogativo alla base dell’intero progetto: l’Erasmus si configura come un’esperienza potenzialmente adultizzante? Nei seguenti capitoli si cercherà di fornire una risposta. 


## CAPITOLO 1
LA TRANSIZIONE ALL’ETÀ ADULTA


### 1.1 Il concetto di giovane: precisazioni terminologiche 
Il presente elaborato si focalizza intorno al concetto di giovinezza. Prima di ripercorrere storicamente lo sviluppo della figura del giovane, è necessaria una riflessione terminologica. 
Il concetto di giovinezza sfugge ad una delimitazione e definizione precise per due motivi. La prima spiegazione consiste nell’evidenza che la definizione canonica del tratto cronologico riconducibile alla giovinezza non corrisponde esattamente alla sua durata biologica. In secondo luogo, la giovinezza può essere intesa come il risultato di un processo di costruzione sociale.
Affermarne la natura socialmente costruita permette di individuare una caratteristica fondamentale: la variabilità. Il significato del concetto di giovinezza, infatti, è estremamente variabile in relazione all’epoca storica e al contesto sociale di riferimento. Ciò implica la difficoltà di creare una definizione universalmente valida e, di conseguenza, la necessità di considerare il contesto socio-culturale e storico per ottenere una fondata storia sociale dei giovani. L’esistenza di una condizione giovanile, perciò, è stata riconosciuta nel corso della storia europea occidentale, pur variando nella definizione dei confini e nel modo di viverla. Tuttavia, è possibile individuarne alcuni caratteri ricorrenti e comuni a tutte le epoche. 
Il primo tratto specifico e ricorrente della giovinezza è identificabile con la liminalità. L’estensione temporale della giovinezza, infatti, è definibile indirettamente collocandola tra le due soglie anagrafiche dell’infanzia e dell’età adulta. La giovinezza, dunque, è un processo di progressiva emancipazione che si colloca “all’interno dei margini mobili tra la dipendenza infantile e l’autonomia dell’età adulta, in quel periodo di puro cambiamento e inquietudine in cui si realizzano le promesse dell’adolescenza, tra l’immaturità sessuale e la maturità, tra la formazione e il pieno dispiego delle facoltà mentali, tra la mancanza e l’acquisizione di autorità e potere” (Levi-Schmitt 2000, p. VI). Il risultato è, dunque, un’età di passaggio caratterizzata da formazione, sperimentazione, trasgressione e autonomia controbilanciate da una condizione di dipendenza in molte altre sfere della vita. 
Una seconda caratteristica comune è una visione lineare della storia della giovinezza, della quale molti studiosi promuovono l’abbandono. Secondo questi ultimi, infatti, non si tratta di un “processo regolare di evoluzione che dalla gioventù della società tradizionali, definita dai suoi ruoli rituali e usanze, giunge sino ad una gioventù moderna, affrancata da ogni costrizione, liberata da tutti i tabù” (Levi-Schmitt 2000, p. IX), seppur le tendenze in atto sembrano dimostrare una certa dinamica evolutiva, ben esemplificata dal miglioramento delle condizioni di vita dei giovani e del configurarsi della giovinezza come un’età della vita a se stante, maggiormente dilazionata nel tempo e desiderabile. 
Ogni società traduce la propria concezione di gioventù in una peculiare rappresentazione di giovane, che varia anch’essa in relazione all’epoca storica di riferimento. Nel costruire questa immagine, la società riflette il proprio sistema di valori e regole relative alla gerarchia di ruoli. 
Considerando le diverse rappresentazioni nel corso della storia, i sociologi Garelli e Offi individuano quattro visioni che hanno caratterizzato la storia sociale dei giovani (Garelli e Offi, 1997, pp. 16-22).
Secondo la prima prospettiva, il giovane è un soggetto da educare attraverso un processo di socializzazione, che consente di acquisire competenze, valori e modelli culturali, costituendo una risorsa spendibile sia a livello sociale che personale.
Ben presto, però, si nota la tendenza di alcuni giovani a non conformarsi alle norme vigenti, fatto che impedisce l’integrazione a fronte di una maggiore emarginazione e che favorisce l’affermarsi di una nuova visione dei giovani, concepiti come un gruppo potenzialmente pericoloso e impersonificato dalla figura del giovane ribelle e marginale, incline alla devianza e alla delinquenza.  
Su questa scia si innesta la terza prospettiva individuata, secondo cui i giovani sono dotati di risorse e qualità che assumono la forma di energia da incanalare, per evitare che si traducano in comportamenti potenzialmente distruttivi. Storicamente, la strategia più efficace è stata quella di favorire la partecipazione dei giovani ad associazioni, che svolgevano anche una funzione di controllo.
Infine, la giovinezza è stata considerata come una qualità svincolata dall’età anagrafica e, in quanto tale, le viene attribuito un giudizio morale che varia dal positivo al negativo. Le ragioni di questa variabile valutazione risiedono nelle diverse visioni e relazioni intergenerazionali imperanti nella specifica società. Pertanto, nelle società giovanilistiche, la gioventù tende ad essere considerata positivamente, esaltandone le doti della freschezza, vivacità e assenza di contaminazioni. Al polo opposto, invece, le società gerontocratiche valutano negativamente il periodo della giovinezza, caratterizzato da atteggiamenti devianti come risultato di incompletezza, incostanza, superficialità e acriticità. 
Dopo aver cercato di delineare i tratti tipici della giovinezza e gli approcci secondo cui è stata studiata, è fondamentale rimarcare l’impossibilità di ricondurla all’interno di categorie chiuse e predeterminate, che impedirebbero di cogliere la declinazione storica e socio-culturale del concetto. Ma come è stata letta la figura del giovane nel corso della storia? Che ruolo era assegnato al giovane all’interno della società? E, infine, è possibile parlare di un “caso italiano” di giovinezza? 
1.2	Excursus storico sul processo di transizione ai ruoli adulti
L’analisi dei principali studi sui giovani, degli approcci di studio impiegati e delle rappresentazioni grafiche maggiormente diffuse permette di ricostruire la storia dei giovani. Dato il carattere non lineare della storia dei giovani, l’obiettivo principale consiste nel cogliere i processi di cambiamento a livello macro nella condizione della giovinezza attraverso le immagini dei giovani che sono state rilevanti nel corso dei secoli, piuttosto che ricostruire una storia che non può essere sistematica. Garelli e Offi (1997) offrono una panoramica storica circa il modo in cui la figura del giovane si è articolata in epoche diverse. Il presente capitolo ha lo scopo di ripercorrere questa storia, prendendo avvio dal mondo greco romano, passando per la realtà dell’Europa medievale, soffermandosi poi sulle dinamiche principali che hanno caratterizzato l’Ottocento e il Novecento, fino alle soglie del terzo millennio, assumendo come punto di riferimento il percorso storico presentato nel sopracitato manuale di Garelli e Offi.
1.2.1 Il mondo greco e romano 
Presso il mondo greco e romano, la giovinezza è un periodo che risulta funzionale alla preparazione dei giovani ai ruoli adulti che saranno chiamati a ricoprire. Durante questo arco di tempo, dunque, sono sottoposti ad un processo di socializzazione e chiamati a sviluppare le proprie qualità, anche in relazione alle mete, ai valori e alle attività istituzionalizzate dalla specifica società. 
Nella Grecia antica, il processo sopracitato assume la denominazione di paidèia, e ha lo scopo di preparare il cittadino attraverso specifici esercizi che consentono di farne emergere le qualità e di apprendere i modelli di comportamento utili a sopravvivere nella città. Inoltre, gli esercizi sono orientati allo sviluppo di abilità militari legati a forza, prestanza fisica e coraggio, senza dimenticare le gare sportive e l’educazione alla caccia, strumento fondamentale per conoscere il territorio e controllarlo in vista delle necessità difensive e offensive richieste dalle situazioni di guerra. Ad Atene, però, si valorizzavano anche le abilità intellettuali, che includevano l’esercizio della scrittura, della filosofia e della retorica, considerate utili nella vita quotidiana e nell’ambito economico-commerciale. 
Il processo di educazione avveniva sotto l’attenta guida degli adulti, i paidagògos, spesso schiavi a cui era affidato il ruolo di precettore, e culminava nell’ingresso del mondo degli adulti attraverso rituali di passaggio predefiniti. Ruoli e rituali, però, erano differenziati sulla base del genere. Le ragazze, escluse dall’attività politica e relegate alla dimensione della casa, venivano formate al ruolo di spose e madri, in grado di garantire la sopravvivenza della città attraverso la riproduzione biologica. Tuttavia, la loro estromissione della vita pubblica non era completa poiché potevano partecipare a rituali pubblici, prevalentemente di carattere religioso, che sancivano il loro progressivo ingresso nella vita adulta, che terminava ai 14 anni, con il raggiungimento dell’età da marito. Tuttavia, occorre sottolineare come le sporadiche partecipazioni alla vita cittadina avvenissero sempre sotto il controllo degli uomini che, invece, erano formati per diventare guerrieri e cittadini. La disparità dei ruoli e la minore rilevanza delle donne nel mondo greco sono testimoniate anche dall’analisi delle rappresentazioni iconografiche dei giovani, realizzate su vasi e anfore. Si nota, infatti, un predominio di scene educative tipicamente maschili, che rappresentano giovani impegnati in attività fisiche e di caccia, che evidenziano il vigore e la forza dei corpi, spesso rappresentati nudi e glabri per distinguerli dagli adulti. 
Anche nel mondo romano è possibile individuare una fase di giovinezza che si estende tra la vestizione della toga virile, segno d’appartenenza alla sfera degli adulti e assunta nel corso della cerimonia rituale dei Liberalia, e la fine del tirocinium, percorso di preparazione ai ruoli adulti attraverso l’insegnamento della disciplina, del diritto e dell’oratoria, oltre all’addestramento militare. Seguendo il vigente criterio di Varrone, l’individuo è considerato adulescens tra i 15 e i 30 anni, iuvenis tra i 30 e i 45. Considerare iuvenis, quindi non pienamente adulto, un soggetto tra i 30 e i 45 anni implica un prolungamento sociale della giovinezza. Questo fatto è spiegabile tenendo conto che la condizione giovanile nel mondo romano è caratterizzata da una relazione di subordinazione inserita in un ordine fortemente patriarcale. La dilatazione temporale della giovinezza, seppur in parte ridotta, è causata dall’esercizio della patria potestas da parte del pater familias. Alla figura paterna, infatti, è riconosciuto il potere di vita e di morte, oltre al diritto di decidere l’avvenire dei figli, che sono sempre più dipendenti dalla famiglia d’origine, anche perché i beni dei genitori venivano ereditati solo successivamente alla morte del padre. I giovani romani, dunque, “costretti per legge a prestare obbedienza al padre a prescindere dall’età, limitati nella loro autonomia economica e nelle loro possibilità decisionali, […] restavano a lungo in una particolare condizione di giovinezza, estromessi da uno dei principali ruoli adulti dell’intero sistema di organizzazione della società romana: quello di padri” (Garelli-Offi 1997, p. 30). Tuttavia, occorre notare che si tratta di una dilatazione temporale relativa, spesso ridotta ad un influsso delle decisioni paterne sulla vita dei figli e con un’estromissione dai ruoli adulti solo parziale, poiché molti giovani ricoprono cariche importanti nella magistratura e nell’esercito. 
Così come accadeva nel mondo greco, anche presso i romani è visibile un notevole controllo degli adulti, esemplificato dalla figura paterna, e che genera frizioni e conflitti generazionali, guidati dal desiderio di distruggere quel rapporto di potere asimmetrico che permette di raggiungere la piena autonomia solo dopo la scomparsa del genitore. 
Si può notare un’ulteriore somiglianza nella transizione ai ruoli adulti nei due mondi, ovvero la rimarcata differenza tra i sessi. Ancora una volta, il criterio di identificazione delle donne non è l’età ma la loro condizione sociale e vengono considerate donne rispettabili solo in quanto mogli e matres, escluse dalla vita pubblica, ad eccezione delle poche figure femminili che godevano di un certo ruolo in ambito religioso, come nel caso delle sacerdotesse consacrate alla dea Vesta. 

1.2.2 Essere giovani nel Medioevo 
 Nel corso dell’epoca medievale, i giovani non sono socialmente intesi come un gruppo a se stante. L’età, infatti, non era considerata un criterio distintivo importante, “non doveva affatto costituire un elemento di separazione, ma piuttosto stabilire dei rapporti regolati da norme di iniziazione che legavano strettamente i piccoli ai maggiori” (Ariès 1960, p.174, cit. in Garelli e Offi 1997, p. 37). La difficoltà di individuare una classe di giovani è legata al mescolarsi di bambini, adolescenti e adulti tanto in ambito lavorativo che educativo, ma soprattutto all’elevato tasso di mortalità che caratterizza il Medioevo a causa di pestilenze, guerre e carestie. In questo contesto, perciò, i “giovani adulti” erano la maggioranza.
Tuttavia, ciò non implica l’assenza di una fase della vita definibile come giovinezza che, però, risulta una condizione profondamente diversa dall’accezione che assume con la modernità. Secondo Garelli e Offi (1997), in questo periodo si assiste alla tematizzazione del concetto di giovane e giustificano la loro affermazione individuando tre prove fondamentali.
In primo luogo, esistono due classificazioni dell’esistenza umana. In particolare, nella cultura popolare si associano le età alle stagioni, per cui l’infanzia coincide con la primavera, la giovinezza con l’estate, l’adultità con l’autunno e la vecchiaia con l'inverno, anche se le età della vita tendono ad essere identificate perlopiù con i ruoli ricoperti. 
In secondo luogo, la distanza tra bambini e adulti è sicuramente minore, con i primi che vengono inseriti precocemente nel mondo dei grandi, ma che rimangono comunque soggetti dipendenti dall’autorità dal capofamiglia senza raggiungere ancora la piena autonomia. La piena indipendenza, infatti, si otteneva dopo aver ricevuto l’eredità paterna, dopo il matrimonio o dopo aver preso i voti. Anche nell’epoca medievale, il passaggio è segnato da un rituale: l’apprendistato. L’apprendistato, che cominciava all’età di sette anni, era funzionale tanto all’acquisizione di capacità lavorative, quanto all’iniziazione alla vita adulta. Come già notato per il mondo greco e romano, dunque, la giovinezza è considerata un periodo preparatorio ai ruoli adulti. 
Infine, l’esistenza di una fase di giovinezza è testimoniata dall’iconografia medievale. In linea con la valorizzazione socio-culturale della cultura cristiana, i soggetti maggiormente rappresentati sono i giovani protagonisti di narrazioni bibliche ed evangeliche. È importante notare come il modo di rappresentare i giovani rispecchi la loro condizione all’interno della gerarchia sociale medievale. I giovani, infatti, erano raffigurati attraverso la tecnica degli scarti che si esprime attraverso la differenza di altezza, con i giovani dipinti con una statura superiore a quella dei bambini ma inferiore agli adulti, e attraverso il loro posizionamento nel dipinto, venendo collocati lateralmente per segnalare la loro marginalità. Da queste rappresentazioni emerge esattamente la tipologia di giovane dell’epoca: un soggetto costretto all’entrata precoce nel mondo adulto ma che rimane in una condizione di autonomia relativa, dipendenza e subordinazione all’interno della scala gerarchica medievale. 

1.2.3 La giovinezza nell’Europa preindustriale   
L’epoca preindustriale riconosce l’esistenza della giovinezza come uno stadio intermedio tra infanzia ed età adulta, anche se più circoscritto rispetto alle definizioni precedenti. La giovinezza, infatti, si estende dagli 8/10 fino ai 25/28 anni, creando uno slot temporale che inizia con l’entrata nel mondo del lavoro o all’accesso agli studi e termina con l’eredità delle proprietà familiari e il matrimonio, che è il criterio discriminante per accedere pienamente al ruolo di adulto. I ragazzi, dunque, vengono considerati adulti in quanto capofamiglia, mentre le ragazze in quanto donne sposate e mogli del capofamiglia, ruoli che dipendono spesso dalle strategie familiari messe in atto. Tuttavia, l’adolescenza non era così socialmente definita e le soglie potevano variare, anche se la costante di questa fascia d’età si può ricondurre ad una situazione di subordinazione dei figli rispetto ai padri, tra cui non sono rari i rapporti conflittuali. 
È possibile individuare una seconda accezione del termine giovinezza. Tra le classi colte, infatti, si diffonde il seme dell’idea moderna di “gioventù come moratoria, cioè di un’economia di vita pronta a una rinuncia temporanea nella speranza di una carriera futura e di migliori opportunità finanziarie, […] un periodo di formazione che dura molti anni, in larga misura sciolto da necessità di guadagno” (Schindler 2000, p. 311, cit. in Garelli e Offi 1997, p. 45). In questo senso, la giovinezza comincia ad essere considerata un’età a sé e prolungata, pur rimanendo una prerogativa esclusiva dell’aristocrazia. 
Sulla scia degli studi condotti da Ariès (1960), Garelli e Offi (1997) individuano due cambiamenti fondamentali che si verificano all’inizio dell’età moderna. Il primo consiste nel mutamento del sentimento dell’infanzia, che comincia ad essere concettualizzata come un mondo separato, con precise caratteristiche. I bambini cominciano a ricevere più attenzioni e vengono posti al centro di considerazioni morali ed educative, con studi sullo sviluppo e preoccupazioni per la loro salute. Il secondo, invece, è rappresentato dall’istituzionalizzazione del collegio, al cui interno si svolgono le lezioni e che separa il mondo dei giovani dal resto della società adulta. 
Ricordare questi due eventi significa riconoscere un cambiamento di mentalità che porta a valutare e diversamente le età della vita ed è una tappa preliminare per la costruzione sociale della giovinezza come un periodo distinto, dotato di proprie specificità e da studiare in quanto tale. Nonostante queste prime avvisaglie di un mutamento nella visione dei giovani, questi ultimi non costituiscono ancora una presenza autonoma sulla scena pubblica, poiché gli adulti vi esercitavano un forte controllo. Presso le società europee preindustriali prevale un’idea di gioventù connotata negativamente dal punto di vista morale, con i giovani tacciati di immaturità e condannati per intemperanza, sfrenatezza e debolezza d’animo. Gli adulti affrontano questa realtà esercitando il proprio controllo attraverso la creazione delle societates juvenum, associazioni giovanili e gruppi organizzati che “contribuivano al controllo sociale dei giovani, […] incanalando in modalità di comportamento socialmente accettate le energie dei molti giovani” (Garelli e Offi 1997, p. 41). 
Tra il Seicento e il Settecento, perciò, cominciano a delinearsi le prime modifiche all’idea fino ad allora imperante di gioventù che perde il carattere di età superficiale e sovversiva, acquisendo quello di “età dell’apprendimento” che, però, continua a convivere con alcune vecchie tendenze di fondo. 

1.2.4 Ottocento e Novecento 
Il verificarsi del processo di modernizzazione e i conseguenti mutamenti strutturali su più livelli incidono sulla condizione dei giovani che può essere definita in transizione. In seguito alla trasformazione delle unità familiari, che smettono di essere unità produttive per diventare unità economiche, si verifica quella che Mitterauer definisce “l’integrazione dei giovani nella famiglia” (Mitterauer 1986, p. 119, cit. in Garelli e Offi 1997, p. 60). Quest’integrazione passa dalla configurazione di un nuovo rapporto tra le generazioni. I figli non sposati, infatti, allungano la propria permanenza all’interno del nucleo familiare, all’interno del quale assumono un ruolo importante dato che contribuiscono al bilancio familiare con il proprio salario. Disporre di un reddito indipendente dall’eredità paterna ha un doppio effetto. Il primo è rendere i giovani più autonomi dal controllo degli adulti, riducendo quella condizione di semi-dipendenza tipica della giovinezza. Il secondo effetto, che può sembrare contraddittorio, è legato al persistere del concetto di eredità, che però assume la forma del lavoro. La famiglia, perciò, continua ad esercitare un forte controllo sulla vita dei giovani sorvegliandone il lavoro, anche con lo scopo di percepirne il reddito. 
A cavallo tra Ottocento e Novecento, si sviluppano delle tendenze che pongono le basi per la formulazione moderna del concetto di gioventù e che, in parte, sono in atto ancora oggi. Proprio durante questo periodo, infatti, avviene la “scoperta dell’adolescenza” (Gillis 1981, pp. 113-152, cit. in Garelli e Offi 1997, p. 66). La fase della vita compresa tra i 14 e i 20 anni comincia ad essere riconosciuta socialmente come una tappa a sé del processo di formazione degli individui, distinta dall’infanzia per l’accesso al mondo del lavoro. Il pieno riconoscimento del ruolo d’adulto, però, è sancito ancora dalla coscrizione militare obbligatoria, considerato un rito di passaggio, e dal matrimonio che, per le donne, coincide anche con la fine del periodo lavorativo.
Garelli e Offi (1997), secondo una prospettiva costruzionista, individuano i fattori alla base della costruzione sociale dell’adolescenza. L’abbassamento della mortalità infantile modifica le strategie familiari, permettendo di mettere al mondo meno figli a cui possono essere riservate più cure e un’educazione migliore per un periodo maggiore di tempo, anche perché i figli diventano i fini della strategia familiare, non più i mezzi, e prevalgono il rapporto è caratterizzato più dall’affetto che dal potere. Un secondo fattore incisivo è stato l’affermarsi della scolarizzazione secondaria, che tende a coincidere con la durata socialmente definita dell’adolescenza e ad assumere il ruolo educativo prima esercitato dalla famiglia d’origine. 
Tuttavia, la nascita di una nuova sensibilità basata sugli ideali di protezione e tutela verso i giovani convive con la diffusione dell’idea secondo cui esiste una correlazione tra giovinezza e devianza. L’essere adolescenti, dunque, sembra portare con sé una potenziale devianza, considerata insita nel mondo giovanile, indipendentemente dalla classe sociale d’appartenenza. La visione dei giovani come gruppo sociale potenzialmente pericoloso e deviante, alimentata dalle condizioni di degrado delle periferie urbane che favoriscono la microcriminalità e dalla presunta tendenza rivoluzionaria della gioventù critica verso l’ordine vigente, portano la borghesia europea a ritardare l’ingresso dei giovani in posizioni di responsabilità a livello politico e sociale. Come conseguenza, comincia a svilupparsi la moratoria, con l’allungamento della scolarità e le elevate soglie di accesso alla vita politica. Nei primi decenni del Novecento si diffonde, dunque, l’equazione gioventù – spreco di energie e il mito del giovane virile come espressione di un “non controllabile disordine” (Calabrese 1988, p. 87, cit. in Garelli e Offi 1997, p. 75). 
Infine, occorre notare il declino della visione della giovinezza come una fase di statica attesa, in vista del matrimonio e dell’eredità, sostituita da una concezione dinamica che configura la gioventù come un periodo di formazione che ritarda l’assunzione dei ruoli adulti, anche se permangono ancora rituali che determinano il passaggio a fasi successive della vita.   
Tra il secondo dopoguerra e gli anni Sessanta, si consolida la tendenza dei giovani a costituirsi come gruppo sociale autonomo, formando la “prima generazione” (Piccone Stella 1993, p. 11, cit. in Garelli e Offi 1997, p. 93) a livello locale, non ancora nazionale. Le ricerche sociali dell’epoca, focalizzate sul rapporto con le principali agenzie di socializzazione e orientate a cogliere gli effetti dei mutamenti sociali sui giovani, consegnano un’immagine di giovane integrato nel sistema sociale, disimpegnato in politica, “consumista, amante della privatezza, giovane delle “3M” (macchina, mestiere, moglie o marito)” (Allum-Diamanti 1986, p. 28, cit. in Garelli e Offi 1997, p. 93). I giovani, infatti, riconoscono e si allineano ai valori tradizionalmente considerati importanti, tra cui il lavoro e l’istituzione sociale del matrimonio, ma diventano portatori di vecchie e nuove tendenze che convivono nello stesso individuo. Tra le nuove tendenze troviamo la rivalutazione dell’istruzione secondaria come mezzo per favorire la propria mobilità sociale e migliorare le condizioni di vita; l’attenzione per gli aspetti materiali della vita legata all’identificazione dei giovani con i beni di consumo emergenti e le nuove mode culturali, tra cui il nascente rock and roll; l’importanza che comincia ad assumere l’individualismo; la valorizzazione del tempo libero. Il configurarsi della gioventù come autonoma rispetto al resto della società genera timore negli adulti che, non potendo più esercitare un controllo totale sui giovani sempre più distanti dai modelli e dagli stili di vita dei genitori, cominciano a parlarne come un problema sociale. D’altro canto, questa paura è compatibile con i primi segni di innovazione da parte dei giovani. Le decisioni sono sempre più prese in autonomia, distanziandosi dalle biografie dei padri e prolungando il periodo degli studi; il nuovo rapporto tra i sessi favorisce comportamenti sessuali più liberi; la centralità del gruppo informale di amici è la base per la formazione di un mondo a sé, con modelli culturali specifici della generazione dei giovani, quasi un abbozzo delle future subculture giovanili. 
I movimenti studenteschi del Sessantotto rappresentano un’altra tappa fondamentale per la costituzione dei giovani come gruppo a sé. In primo luogo perché, per la prima volta, i giovani agiscono come un soggetto collettivo, consapevoli di essere un gruppo sociale a parte e diventando protagonisti della scena politica. Ciò permette ai giovani di essere percepiti e riconosciuti anche dal resto della società, con la quale si crea un influsso reciproco, per cui non solo i cambiamenti della società influiscono sui giovani, ma anche quest’ultimi incidono sulla società. In secondo luogo, è il primo movimento di generazione, composto da giovani accomunati dalla stessa subcultura, consapevolezza della loro condizione e dei problemi sociali dell’epoca. Il loro dissenso nasce da ciò che Statera (Statera 1973, p. 34, cit. in Garelli e Offi 1997, p. 117) definisce “emancipazione sotto tutela”: i giovani hanno sviluppato una nuova maturità culturale, ma la piena indipendenza rimane loro inaccessibile a causa della dipendenza economica dalla famiglia e dall’indeterminatezza del ruolo dell’adulto, “sempre meno acquisito in modo univoco a seguito di una specifica formazione all’interno delle istituzioni educative” (Garelli e Offi 1997, p. 118), che hanno sempre più un effetto di segregazione. La scuola, infatti, è già in una fase di isolamento dal mondo produttivo, per cui l’istruzione fallisce nel trasmettere gli strumenti utili per l’ingresso nel mondo lavoro e richiama a sé tutti i giovani non ancora integrati. Comincia così a diffondersi il fenomeno della disoccupazione giovanile che, insieme all’aumento del tempo dedicato allo studio, hanno l’effetto di allungare la fase della giovinezza, in un contesto in cui il passaggio dalla condizione di giovane allo status di adulto dipende fortemente dall’accesso al mondo del lavoro. Se i giovani però sono relegati ai margini dell’organizzazione sociale, risultano perfettamente integrati nel sistema in quanto consumatori, che dispongono di maggiori quantità di denaro rispetto al passato, e in quanto principali destinatari delle iniziative proposte per il tempo libero, sempre più orientato verso le attività che adatte ad un uso privatistico dei beni di consumo. 
Nel presentare i protagonisti degli anni Settanta, Garelli e Offi (1997) li definiscono come la “generazione di mezzo”, promotrice del cambiamento e vittima delle sue contraddizioni. Sono gli anni della formazione di una società pluralistica, caratterizzata da nuove forme di espressione socioculturale e di sperimentazione delle alternative degli stili di vita. In questo contesto, circolano due rappresentazioni dei giovani. La prima visione è esplicata dalla metafora del “riflusso”, promossa dagli adulti che interpretano il declino dell’impegno socio-politico, la disoccupazione e il rifiuto dei riferimenti tradizionali e istituzionali non più in grado di rispondere ai bisogni dei giovani, come sintomi di una tendenza tipica dei giovani a ripiegarsi su sé stessi, privilegiando la dimensione della vita privata rispetto all’impegno pubblico. Spiegato con le parole di Allum e Diamanti, “Da soggetto emergente e protagonista del cambiamento, i giovani paiono così ridursi a “soggetto sommerso […]” (Allum e Diamanti 1986, p. 20, cit. in Garelli e Offi 1997, p. 141), in netto contrasto con il protagonismo politico del decennio precedente. Conseguentemente i giovani, privati del loro potenziale dirompente di cambiamento, non appaiono più come un gruppo sociale pericoloso per la stabilità della società. I giovani, però, tendono a non riconoscersi in questo ritratto, privilegiando altri caratteri tra cui Garelli e Offi (1997), sulla base dell’analisi di altri studi, notano due principali tendenze. La prima è il fatto che i giovani siano “senza padri né maestri” (Ricolfi-Sciolla 1980, p. 247, cit. in Garelli e Offi 1997, p. 143) a causa della modifica del processo di formazione dei valori, che cessa di essere a trasmissione verticale per diventare orizzontale e intragenerazionale. Gli elementi tradizionalmente importanti per la formazione dei valori, come la famiglia, l’origine di classe e l’istruzione, sono ora ridimensionati e sostituiti da nuovi elementi, tra cui l’esperienza lavorativa e le reti di relazioni e di socializzazioni esterne alla famiglia e alla scuola. La seconda, invece, è l’emergere di un profondo disincanto verso le tradizionali ideologie, che si riconoscono come punti di vista parziali sul mondo e non più verità assolute e totalizzanti. In entrambi i casi, le protagoniste di queste tendenze sono le ragazze, che non solo si proiettano verso il contesto extradomestico, opponendosi alle scelte formative imposte dai genitori, ma si caratterizzano per un maggiore distacco dai modelli culturali della generazione precedente e per un minore condizionamento nella creazione dei propri valori, dove i meccanismi verticali non hanno più alcun peso, al contrario di quanto si registra tra i ragazzi. 
La vera svolta per la definizione della giovinezza in senso moderno avviene negli anni Ottanta e Novanta del secolo scorso. Proprio in questo periodo si manifesta un nuovo interesse per i giovani espresso dall’aumento degli studi che li pongono al centro dell’attenzione pubblica. L’incremento è spiegabile con l’esigenza di controllare i comportamenti sociali; il governo di partiti attenti ai processi giovanili considerati cruciali per gli equilibri futuri; l’effetto della crisi economica sui giovani; l’obiettivo di conoscere gli orientamenti, gli obiettivi e i modelli dei giovani in quanto capaci di anticipare i fenomeni sociali futuri. Molti studi cominciano a notare un cambiamento nella ricerca sui giovani. In particolare, Capecchi (1982), osserva come gli studi, per ovviare ad un “disagio interpretativo” dovuto anche alla mancanza di una definizione precisa di “giovane”, abbandonano l’uso di categorie e schemi interpretativi univoci che impediscono di cogliere i cambiamenti in atto nella condizione giovanile che avvengono in una situazione di elevata complessità sociale rispetto al passato. 
Garelli (1997) interpreta l’emergere di una condizione giovanile diversa da quelle passate come il riflesso di un contesto socio-culturale sempre più complesso e differenziato. La nuova generazione di giovani è caratterizzata dalla definizione di un peculiare modello di realizzazione i cui tratti distintivi sono la pluralità e la sperimentazione. I giovani, infatti, valorizzano al massimo l’esperienza personale che si compone di una molteplicità di appartenenze, ruoli e attività, spesso anche in contraddizione tra loro ma mai intesi come totalizzanti. L’esperienza scolastica e il lavoro continuano ad avere importanza, ma vengono ridefiniti. Lo studio è ciò che permette non solo di acquisire competenze funzionali ad un inserimento di successo nel mercato di lavoro, ma è anche ciò che permette di arricchirsi culturalmente, spesso combinandolo con attività lavorative simultanee, e in un ambiente che favorisce il dialogo costruttivo con gli insegnanti. Allo stesso modo, avere un lavoro stabile rimane una condizione necessaria per accedere all’indipendenza economica, ma nella ricerca dell’occupazione è fondamentale tenere in conto il livello di realizzazione personale che può garantire. Infine, si crea un rapporto flessibile con agenzie di socializzazione, tra cui le istituzioni e la famiglia rivalutata per la funzione affettiva, e che si costituiscono come fonti da cui i giovani attingono selettivamente elementi funzionali alla propria realizzazione personale. Il venir meno dell’azione totalizzante delle istituzioni tradizionali e la messa in discussione del modo tradizionale di fare politica fanno emergere l’importanza dell’appartenere a più di un gruppo di pari. Il gruppo di pari diventa il luogo in cui sperimentare le relazioni, confrontarsi ed elaborare valori e orientamenti culturali in un clima libero, autonomo, affettivo e privo di gerarchie. Nella formazione dei modelli, pertanto, prevalgono le dinamiche orizzontali delle interazioni tra pari. 
Il giovane che si affaccia alle soglie del Duemila, dunque, è un soggetto che “in luogo di confinare la sua esistenza in ambiti ristretti e ufficialmente riconosciuti tende a sperimentare e a conoscere in modo autonomo, nel tentativo di essere attivo nel determinare la propria vita quotidiana […] e scandisce la sua esistenza in molti ambienti, aspetto questo che lo porta a valorizzare le diverse appartenenze per i positivi e specifici apporti che ognuna è in grado di garantire alla sua esistenza” (Garelli-Offi 1997, p. 156). Si configura così un’identità flessibile e di debole intensità che consente al soggetto di adattarsi alle diverse realtà, muovendosi come pendolari tra varie opportunità e ruoli, inserendosi nel sistema sociale in maniera più elastica rispetto al passato. La giovinezza, dunque, si costituisce più come una “condizione” che assume valori e significati diversi, piuttosto che come un “processo” composto da tappe prestabilite che portano ad un esito prevedibile dell’accesso ai ruoli adulti. Le tappe diventano reversibili e disordinate, connotando la giovinezza come un periodo di attesa dai risvolti molteplici che non sempre tendono verso lo status adulto. Inoltre i giovani, pur rimanendo in una condizione di dipendenza dalla famiglia d’origine, cominciano a sperimentare l’autonomia in altri campi come il tempo libero, i consumi e la sfera affettiva. 
Date queste condizioni, il tempo della condizione giovanile si prolunga. Se in passato i giovani si inseriscono con celerità nel mondo adulto, nella società contemporanea si assiste ad uno stato di moratoria, ovvero di giovinezza prolungata, nel quale i giovani rinviano il momento dell’accesso ai ruoli adulti, che richiedono un investimento maggiore di tempo e risorse per essere raggiunti. 
I giovani del Terzo millennio: cambiamenti e tendenze recenti       
La condizione dei giovani nel Terzo millennio può essere delineata a partire dai principali risultati del progetto EXCEPT e presentati nel libro curato da Sonia Bertolini, Giovani senza futuro? (2018). EXCEPT (Social Exclusion of Youth in Europe. Cumulative Disadvantage, Coping Strategies, Effective Policies and Transfer) è un progetto finanziato dalla Commissione Europea all’interno del programma di ricerca Horizon2020 e che ha coinvolto nove paesi per una durata di trentasei mesi (http://www.except-project.eu). Attraverso una ricerca mixed-method, il progetto si pone l’obiettivo di studiare la condizione giovanile in Europa considerando l’effetto che fattori macro (es: trasformazione nel mondo del lavoro, globalizzazione, flessibilizzazione), meso (filtri istituzionali: sistema educativo, regime di welfare, sistemi familiari) e micro (risorse personali) hanno sui corsi di vita individuali, cercando di comprendere il nesso tra insicurezza lavorativa e rischi di esclusione sociale. Il quadro che emerge evidenzia come i vissuti dei giovani europei del Terzo millennio siano caratterizzati da una crescente incertezza causata dai veloci cambiamenti economici e sociali. L’incertezza lavorativa e l’insicurezza hanno sì un impatto diverso a seconda del contesto istituzionale in cui i giovani sono inseriti, ma producono una generale tendenza alla posticipazione delle transizioni alla vita adulta e ad adottare una concezione di autonomia al ribasso, per cui la maggior parte dei giovani può definirsi solo parzialmente autonoma disponendo di entrate limitate che non permettono la transizione. 
In un contesto di difficile transizione, sempre più rimandata nel tempo e concepita come reversibile, i giovani tendono ad attuare una sospensione delle scelte fondamentali che li inserisce in una situazione di ambivalenza, caratterizzata dalla tensione tra la domanda di vita autonoma e l’accettazione di una situazione di dipendenza. Inoltre, la situazione è complicata dal disintegrarsi di un modello unico di transizione a favore del proliferare di molteplici modalità di accesso ai ruoli adulti e per cui i giovani mettono in campo un modello di realizzazione aperto e policentrico, volto a cogliere tutti gli stimoli che si presentano loro piuttosto che procedere poche scelte fondamentali e unitarie. 
In una gioventù che si estende e non è più intesa come propedeutica ad ottenere lo status adulto, i giovani sono soggetti ad una dipendenza prolungata, pur sperimentando l’autonomia in altre sfere. Essi si trovano dunque in uno stato di indeterminatezza, di autonomia e dipendenza simultanea poiché, se in alcuni campi giocano al rinvio procrastinando le decisioni, in altri sono degli anticipatori, assumendo già i ruoli di adulti pur non essendo completamente indipendenti dalla famiglia d’origine. Nel momento in cui i giovani accedono al mondo adulto, perciò, essi possono già aver sperimentato la vita autonoma ed estendono il modello sperimentale anche ad altre dinamiche. 
1.3 Il peculiare caso italiano 
In Italia, il processo di transizione all’età adulta si configura come un caso peculiare che richiede di essere analizzato. Nel contesto italiano sono in atto le tendenze precedentemente delineate, ma si caratterizza soprattutto per essere il paese in cui il rallentamento dell’assunzione dei ruoli adulti è più visibile. La rilevazione EUROSTAT del 2016 compiuta su un campione di giovani tra i 18 e i 34 anni, mostra come la maggiore differenza tra i ragazzi italiani e i coetanei europei si riscontri sul piano dell’autonomia abitativa. Si nota come il 65% dei giovani italiani viva ancora con i genitori, a fronte di una media europea del 48%, pur confermando il trend europeo per cui sono le donne a lasciare prima la casa di origine rispetto ai figli maschi. 
Prima di procedere con l’individuazione delle cause che rendono il caso italiano così particolare, è necessario considerare un cambiamento più generale. 
La letteratura sociologica analizza l’età giovanile come una condizione transitoria, orientata al raggiungimento dell’età adulta attraverso il superamento di “cinque grandi transizioni” (Settersten, 2007) costituite da cinque socialmente necessarie e attese che conducono dalla giovinezza all’età adulta. Le cinque soglie sono rappresentate da: conclusione del percorso scolastico; ingresso stabile nel mercato del lavoro; uscita dalla famiglia d’origine; neo-località e creazione di un nuovo nucleo familiare; genitorialità. 
Secondo la concezione tradizionale della transizione all’età adulta, le tappe formano una sequenza predefinita nell’ordine e nei contenuti. Ciò prevede che le tappe siano conseguite e superate come soglie irreversibili, per cui si deve procedere necessariamente al superamento della tappa successiva. 
Le rilevazioni sui giovani in Italia condotte dall’Istituto IARD tra gli anni Ottanta e il Duemila colgono la trasformazione nell’auto-percezione dei giovani, per cui si registra una desincronizzazione delle soglie di transizione. Nell’epoca moderna, i corsi di vita non sono più standardizzati, bensì strutturati in maniera più flessibile e caratterizzati da una “crescente diversità nel sequenziamento e nelle tempistiche dei marcatori del ciclo di vita degli adulti, che sembra non corrispondere ai modelli più lineari e ordinati del passato” (Brückner, Mayer, 2005). Si assiste così alla posticipazione delle tappe, non più superate nello stesso momento da tutti i giovani e al prolungamento degli intervalli tra uno step e l’altro. In particolare, il dilatamento della transizione all’età adulta e l’ampliamento dell’intervallo tra la prima e l’ultima soglia hanno reso necessario ampliare il campione degli intervistati nell’ambito delle rilevazioni IARD, alzando la fascia d’età fino ai 34 anni per osservare il superamento delle soglie di transizione, soprattutto il divenire genitori.
In secondo luogo, le tappe sono sempre meno superate nella sequenza prefissata. Questo fenomeno è esemplificato dall’emergere della figura dello studente-lavoratore, il quale può accedere al mercato del lavoro, seppur in modo precario, già prima di terminare il percorso scolastico, e di nuovi percorsi di acquisizione dell’autonomia, per cui l’uscita dalla famiglia d’origine non esclude la possibilità di un ritorno in caso di mancanza di indipendenza economica. 
Infine, le soglie sono sempre meno percepite come irreversibili. La propria biografia non è composta da scelte ed esperienze irrevocabili, bensì l’individuo può muoversi tra le tappe in maniera trasversale, creando il proprio percorso attraverso decisioni che non sono mai date una volta per tutte, non conducono a effetti irreversibili e non rappresentano momenti di turning point che impongono l’inizio della fase successiva. La transizione all’età adulta, dunque, assume nuove e molteplici forme, in cui i percorsi di acquisizione dell’autonomia sono sempre più diversificati e singole esperienze della propria traiettoria possono simbolicamente segnare la transizione adulta. Il giovane, inoltre, ha una percezione della propria vita sempre più autodiretta, in cui si ha la libertà di compiere scelte che possono essere riviste, non sono più decisive.  
Come influisce il cambiamento sopra descritto sulle cinque “grandi transizioni” già menzionate? Per quanto riguarda il termine del periodo formativo, nelle generazioni precedenti la permanenza nel sistema scolastico si collocava all’interno di confini temporali precisi, che oggi si dilatano e perdono la loro irreversibilità, continuando anche in corrispondenza del superamento di altre tappe. L’accesso continuativo al mercato del lavoro si raggiunge sempre più tardivamente sia per la propensione a continuare gli studi, determinando l’allungamento del periodo formativo, sia per la trasformazione avvenuta nel mondo del lavoro, che lo rendono sempre più flessibile e caratterizzato da contratti temporanei. I giovani che hanno conseguito un titolo di studio riescono a trovare lavoro più rapidamente rispetto al passato ma, nonostante ciò, un quarto dei giovani che hanno superato i trent’anni non è ancora inserito nel mercato del lavoro. 
Relativamente alla terza soglia, l’uscita dalla casa dei genitori e l’ottenimento dell’indipendenza economica, si registra l’allungamento della permanenza nella famiglia d’origine. In Italia, questo fenomeno assume dimensioni senza paragoni e viene definito come la tendenza alla famiglia lunga. 
Anche la tappa successiva, rappresentata dalla neo-località attraverso la creazione di una nuova famiglia, assume tratti specifici in Italia. La creazione di una nuova famiglia, infatti, tende ad avvenire prevalentemente in maniera tradizionale, ovvero conseguentemente al matrimonio. Ciò è dovuto alla mancanza di forme intermedie di convivenza esterna al nucleo familiare, maggiormente diffuse nei Paesi del Nord Europa, che facilitino il passaggio del giovane dal nucleo familiare originario a quello nuovo. L’ultimo step è la genitorialità, in un contesto in cui si tende a spostare il momento del concepimento oltre i trent’anni, slittamento che influisce negativamente su un già basso tasso di fecondità nazionale. 
I giovani sono intesi sempre più come il risultato di un percorso storico, sociale ed economico che ha affrancato dalla necessità di assumere repentinamente i ruoli adulti. Erikson definisce questo periodo come caratterizzato da una condizione di moratoria psicosociale, per cui il lasso di tempo tra l’adolescenza e l’adultità è vissuto come un momento di sospensione dagli obblighi e dalle scadenze legare all’assunzione dei ruoli adulti. In questa nuova condizione di giovinezza prolungata, i giovani hanno la possibilità di sperimentarsi, imparare a vivere e acquisire conoscenze ed esperienze. Ciò implica una nuova concezione del tempo, vissuto come qualcosa di qualitativamente diverso e non necessariamente orientato verso il raggiungimento della fase adulta. Questa condizione, dunque, si oppone alla tradizionale visione della giovinezza come periodo con un forte valore strumentale, propedeutico all’acquisizione celere di specifici ruoli adulti.
1.3.1 La tendenza alla “famiglia lunga”: definizione e cause 
In un contesto in cui i giovani si configurano sempre più come “adulti apparenti, persone che vivono sospese tra l’adolescenza e l’età adulta” (Minta, 2007, p. 29, cit. in Bertolini 2018, p. 21), senza percepirsi né come adolescenti né come adulti, si diffonde la tendenza della famiglia lunga, tratto che rende peculiare il modello italiano di transizione all’età adulta. 
Il concetto di famiglia lunga, definito per la prima volta dai sociologi Scabini e Donati (2002), descrive un modello di permanenza protratta dei giovani italiani nella famiglia d’origine oltre la soglia dei 25 anni, anche quando è stato raggiunto un livello di autonomia economica che permetterebbe di rendersi indipendenti dai genitori. È un modello che determina una coabitazione tra più generazioni, che perde l’antico tratto di conflittualità, ed è particolarmente diffuso nei Paesi dell’Europa meridionale. Si parla di un caso italiano di acquisizione dei ruoli adulti poiché in Italia la posticipazione delle tappe e soprattutto del matrimonio si è tradotta nel prolungamento della permanenza dei giovani nella famiglia d’origine, piuttosto che in un aumento delle convivenze more-uxorio o della diffusione della figura del single indipendente, come è accaduto invece nei paesi nord-europei. 
Nei paragrafi successivi, la generale tendenza italiana alla famiglia lunga verrà delineata in relazione alle differenze che entrano in gioco nel momento in cui si considerano variabili come la classe d’età, il genere, il contesto territoriale di appartenenza e la collocazione sociale. Le considerazioni e i dati di seguito presentati si basano sulla lettura dei rapporti delle indagini che l’Istituto IARD, network di ricerca sulla condizione e le politiche giovanili, ha realizzato nel 2007 in Italia per monitorare la condizione giovanile.
Considerando la variabile dell’età, si nota che il modello della famiglia lunga predomina nelle prime classi di età adulte, per poi stemperarsi in quelle successive a causa di una maggiore presenza di soggetti già coniugati, che hanno avviato una convivenza e di una minoranza di single che vivono da soli. 
Per quanto riguarda la variabile del genere, si registrano minime differenze fino alla soglia dei 24 anni, ma che raggiungono i venti punti percentuali nelle classi d’età successive, con una quota maggioritaria di giovani maschi che vivono presso la famiglia d’origine rispetto alla controparte femminile. In un contesto in cui l’acquisizione dell’autonomia abitativa è ancora strettamente correlata al matrimonio, la differenza è spiegabile con il persistere di un modello di costruzione della coppia che prevede l’asimmetria tra le età dei partner, con le ragazze che registrano un’età al matrimonio minore rispetto ai ragazzi, determinando un’uscita meno tardiva per le prime rispetto ai secondi. 
La diversa appartenenza territoriale determina delle differenze nei tempi e nel modo di transizione. Chi vive nel Sud Italia e in piccoli centri sembra allungare la permanenza nella famiglia d’origine, da cui esce prevalentemente attraverso il matrimonio; al contrario chi abita nelle grandi città del Nord tende a vivere prematuramente una situazione di neo-località non vincolata al matrimonio. 
In relazione alla condizione sociale, si registra il raddoppiamento di coloro che attualmente hanno un lavoro che consentirebbe di raggiungere l’autonomia abitativa, ma nonostante ciò continuano la loro vita in famiglia. Ciò mostra come il modello di famiglia lunga non sia più strettamente interconnesso con l’assenza di un inserimento nel mercato lavoro e alla conseguente mancanza di un reddito personale. Le variabili economiche non perdono la loro centralità, ma nella decisione di uscire dalla famiglia assumono importanza nuovi fattori, tra cui l’importo del reddito guadagnato.
Tanto il sesto rapporto IARD sulla condizione giovanile in Italia quanto i dati raccolti dal progetto EXCEPT, finanziato dalla Commissione Europea e previsto dal programma Horizon 2020 con l’obiettivo di studiare l’esclusione sociale dei giovani in Europa, notano come le cause che spingono i giovani a procrastinare il superamento delle soglie di passaggio, superandone solo una o due e dilatando il tempo che intercorre tra il superamento delle tappe iniziali a quelle successive, sono riconducibili a fenomeni strutturali e di mutamento economico. La discussione delle cause verrà di seguito affrontata facendo riferimento ai testi sopra menzionati.
Il primo fenomeno da considerare è la tendenza alla crescente scolarizzazione e all’aumento della permanenza nel circuito scolastico, che incide negativamente sulla dilatazione dei tempi di transizione. Nel contesto attuale, l’uscita dal percorso scolastico si affranca sempre più dal ruolo di prima tappa del processo di transizione, il cui superamento era necessario per poter passare agli step successivi. Di conseguenza diminuisce la quota di studenti esclusivi, a fronte di un aumento degli studenti-lavoratori. Permanere più a lungo del previsto nel ciclo formativo può essere da un lato la conseguenza di percorsi accidentati, dall’altro può rappresentare una strategia. L’acquisizione di credenziali educative elevate attraverso la prosecuzione dei cicli formativi è, infatti, una delle strategie per aumentare le possibilità di trovare occupazione. Tuttavia nelle percezioni dei giovani, la scuola ha successo nel fornire un bagaglio di conoscenze di base ma fallisce nella sua funzione di formazione, nel trasmettere competenze spendibili e in linea con le richieste del mercato del lavoro.  
Il secondo fattore causale è riconducibile alla precarizzazione del mercato del lavoro, soprattutto nei confronti delle nuove generazioni. Alle soglie del Duemila si registra un’apertura favorevole del mercato del lavoro verso i giovani, che genera una diminuzione degli inattivi e un aumento dei giovani lavoratori, che però non si traduce in una maggiore tendenza a rendersi indipendenti dalla famiglia di origine. Questa correlazione negativa si spiega con il fatto che l’inserimento nel mercato del lavoro avviene sempre più attraverso rapporti di lavoro atipici, caratterizzati da una maggiore flessibilità dei contratti (a tempo determinato, part-time, collaborazioni, interinali) che, se da un lato espandono le opportunità di lavoro, dall’altro rendono il lavoro sempre meno garantito e sicuro. L’incidenza di contratti atipici sembra essere maggiore tra i laureati rispetto ai giovani con qualifiche più basse, anche se per i primi diventa un modo per conseguire migliori opportunità professionali. 
Per quanto riguarda la difficoltà nel superare la soglia di accesso stabile al mercato del lavoro, la situazione italiana è peggiorata dalla carenza di meccanismi istituzionali e strumenti di accompagnamento e del giovane nel passaggio da studente a lavoratore. Nonostante alcuni tentativi di adottare strumenti di orientamento formativo e professionale come tirocini, stage, alternanza scuola – lavoro per far sì che le capacità acquisite nel sistema scolastico rispondessero in maniera ottimale ai profili professionali richiesi dal sistema delle imprese, essi non si sono rivelati così efficaci e sono stati utilizzati solo una minoranza di giovani. Uno degli strumenti meno utilizzati è soprattutto lo stage all’estero, che consentirebbe una migliore integrazione dei giovani cittadini italiani nello spazio socio-economico europeo. 
I medesimi mutamenti nel livello di scolarizzazione e nel mercato del lavoro riguardano anche gli altri paesi nord-europei dove però, a differenza dell’Italia, i giovani continuano a lasciare la casa dei genitori per formare nuclei autonomi. Ciò è possibile perché posticipazione e precarizzazione sono state compensate da politiche pubbliche in grado di garantire sicurezza e autonomia economica dai genitori, mentre in Italia le trasformazioni non sono state accompagnate da politiche e forme di sostegno in grado di attutire la precarietà, per cui l’unica barriera al rischio di povertà rimane la famiglia. La situazione di precarietà esperita dai giovani alimenta una visione negativa del futuro. Il 58% dei giovani attribuisce maggior valore alle esperienze che si possono fare nel presente, piuttosto che alla pianificazione del futuro. La forte insicurezza sperimentata nel mercato del lavoro, infatti, porta a focalizzarsi sul presente a causa di una forte difficoltà a proiettarsi nel futuro. Questa tendenza è confermata dall’analisi delle percezioni dei giovani, in cui emerge la scarsa propensione a pensare che le transizioni si verifichino nei cinque anni successivi. Su questo dato incide la consapevolezza di quanto sia rischioso anticipare scelte importanti e limitanti, piuttosto ai vantaggi dati dal tenersi aperte più strade e possibilità diverse, considerato fondamentale dal 70,4% dei giovani intervistati. 
Dunque, il posizionamento oggettivo nel mercato del lavoro e la sua percezione soggettiva influiscono sulle scelte e le strategie abitative dei giovani italiani. L’assenza di forme di continuità di reddito per far fronte alla discontinuità implicita in un mercato del lavoro flessibile porta alla decisione di posticipare le transizioni e a praticare la “strategia di attesa” (Fullin, 2005; Reyneri, 2011), per cui si utilizza la protezione familiare durante il periodo di ricerca dell’occupazione, o la strategia del ritorno in famiglia in periodi di particolare difficoltà economica, dopo aver sperimentato fasi di autonomia abitativa. 
Dal punto di vista psicologico-soggettivo, i giovani si trovano così a dover compiere scelte fondamentali in una situazione di forte incertezza determinata soprattutto dall’insicurezza lavorativa che rende impossibile prendere decisioni ottimali. La difficoltà di programmare la propria vita nel lungo periodo quando si lavora con forme contrattuali atipiche, orienta verso l’adozione del “meccanismo di sospensione della decisione […], per cui si tende a slittare verso un orizzonte decisionale di breve periodo; diventano problematiche le decisioni self-binding, che hanno ripercussioni di lungo periodo […] per cui diventa razionale posticipare le decisioni che riguardano le transizioni alla vita adulta, perché il processo di ricerca delle informazioni richiede tempo” (Mills e Blossfeld, 2003, p. 188, cit. in Bertolini 2018, p. 60). Ciò comporta un riaggiustamento delle preferenze verso il basso attraverso la costruzione di una nuova retorica che valuta diversamente le tappe di acquisizione dell’autonomia, non considerandole più centrali. In queste condizioni, la coabitazione con il nucleo parentale appare come la norma mentre l’uscita è proiettata in un futuro astratto, senza che vi siano progetti concreti. 
Nei Paesi del Sud Europa dove si registra un ritardo nell’acquisizione dell’autonomia abitativa, si nota anche una ridotta presenza giovanile nel mercato degli affitti. Il sistema abitativo italiano è incentrato sulla casa di proprietà, per cui chi esce dal nucleo familiare d’origine tende a farlo comprando la casa in cui andrà a vivere. La forte insicurezza sperimentata sul mercato del lavoro tende ad alimentare il trend cominciato negli anni Settanta che porta a registrare un aumento costante dell’età al momento dell’acquisto della prima casa. L’assenza di un mercato degli affitti esteso e flessibile in grado di favorire un’uscita precoce, presente nei paesi nord-europei, è un ulteriore freno all’autonomia abitativa. Inoltre, gli ostacoli si incontrano anche a livello istituzionale, con politiche a sostegno dell’abitazione che considerano la casa di proprietà come unica soluzione abitativa e si rivolgono a un segmento ristretto della popolazione giovanile.   
Tuttavia, le ricerche condotte all’interno del progetto EXCEPT, che s’interroga sulle conseguenze dell’insicurezza lavorativa sull’autonomia e sulle scelte economiche, mostrano come ad una posizione contrattuale stabile non sempre corrisponda una situazione di autonomia abitativa, per cui sono molti i giovani che pur avendone l’occasione scelgono di non compiere la transizione. Prolungare la permanenza nella casa parentale è spesso una situazione scelta, una “strategia di risparmio volta a mettere da parte le risorse necessaria per l’uscita […] e la temporaneità della condizione contribuisce a renderla accettabile” (Bertolini 2018, p. 70). Questo dato implica il fatto che la spiegazione del radicamento del modello di famiglia lunga non si esaurisce con il riferimento a variabili strutturali ed economiche. Per ottenere un modello esplicativo in grado di dar conto del caso italiano in maniera completa, è fondamentale considerare le variabili di tipo culturale che inibiscono la scelta anche quando sarebbe possibile. 
In Italia, l’assenza di sostegni istituzionali implica che la famiglia d’origine assuma un ruolo centrale nella transizione all’autonomia abitativa, per cui il sostegno economico della famiglia d’origine è considerato pienamente accettabile. In linea con il persistere di un forte familismo per cui la famiglia ha un prolungato ruolo protettivo nei confronti dei figli anche quando sono giovani-adulti, il supporto dei genitori è una condizione necessaria per raggiungere l’autonomia abitativa. Il supporto può assumere diverse forme e spesso può rappresentare una spinta a rimandare il passaggio all’autonomia o un paracadute contro la precarietà, per cui i giovani provano ad uscire dalla casa dei genitori più di una volta, con un buon 54% che vi ha fatto nuovamente ritorno. All’interno del contesto italiano, perciò, la famiglia gioca un duplice ruolo protettivo. Oltre a fornire un sostegno affettivo e psicologico mantenendo i figli senza chiede nulla in cambio; la famiglia supplisce alle carenze del mercato del lavoro e alla mancanza di sostegno dallo Stato, sostenendo i figli nei periodi di disoccupazione o di ricerca dell’occupazione. In molti casi, inoltre, vivere fuori dal nucleo familiare d’origine non esclude altre forme di dipendenza dai genitori, a differenza del passato in cui l’uscita dalla famiglia segnava un irreversibile passaggio all’età adulta. 
Tra i fattori che ritardano una transizione che avviene intorno ai trent’anni, si annovera il persistere di modelli culturali ed educativi che non favoriscono l’acquisizione dell’autonomia da parte dei figli. Seppur ritardato, il matrimonio continua ad avere un ruolo centrale nel processo di autonomia. Nel contesto italiano, infatti, il fattore di spinta che più determina l’uscita dalla famiglia continua ad essere la creazione di un nuovo nucleo familiare attraverso un’unione stabile, diversamente dai paesi nord-europei dove è diffuso un modello di uscita orientato ad un periodo di sperimentazione e convivenza tra pari, forti dei sostegni economici istituzionali. La resistenza di un modello di uscita basato sul matrimonio sembra dunque ridurre la diffusione di modelli di uscita alternativi, imponendosi come ulteriore ostacolo all’indipendenza. 
Infine, occorre considerare l’effetto della presenza di una debole cultura dell’autonomia abitativa in Italia, che anche sotto questo aspetto si differenzia fortemente dagli altri Paesi europei. Il progetto EXCEPT, presentato nei paragrafi precedenti, oltre ad approfondimenti nazionali prevede anche la conduzione di uno studio comparativo attraverso la realizzazione di interviste qualitative in nove Paesi europei. Dall’analisi delle ricerche condotte nell’ambito del progetto EXCEPT in Svezia e Gran Bretagna (Bertolini 2018, p. 133), emerge un modello educativo volto a favorire l’autonomia abitativa dei figli, intesa come una situazione programmata e auspicabile fin dal termine degli studi superiori, momento in cui i genitori spingono i figli ad andare a vivere da soli. In Italia, invece, l’uscita di casa si configura come l’esito di eventi inattesi o di una scelta effettuata quando le condizioni sono favorevoli ed è l’attitudine della famiglia d’origine a frenare il raggiungimento dell’indipendenza. I genitori italiani, infatti, non considerano l’autonomia abitativa come una priorità educativa e tendono a disincentivarla, consigliando ai figli in difficoltà di rimanere a casa. Questa tendenza tipicamente italiana è spiegabile ricorrendo alla sindrome del “nido vuoto”, per cui i genitori tendono a trattenere i figli per paura che non siano in grado di affrontare le difficoltà e per il desiderio di continuare a svolgere il ruolo genitoriale, mantenendo una posizione centrale nella famiglia. Il risultato di questa tendenza, però, è deleterio. I giovani vivono un processo di lenta transizione, rimanendo in una condizione di deresponsabilizzazione e moratoria che non li aiuta a rendersi autonomi, anche per l’assenza di una pressione sociale ad uscire e per la paura di deludere i genitori andando via “troppo presto” da casa. 
Infine, l’ultimo fattore che richiede di essere sottolineato è il cambiamento avvenuto nel rapporto genitori-figli, che perde il carattere di subordinazione, diventando sempre più aperto al dialogo e paritario. La famiglia lunga, offrendo aiuto e protezione in cambio di una dipendenza relativa più formale che sostanziale, soddisfa i bisogni economici, culturali e psicologici del giovane. La scelta di vivere con i genitori, dunque, appare più conveniente se confrontata con le spese da sostenere vivendo in una condizione di autonomia abitativa.
1.3.2 Nuovi modi di vivere in famiglia e nuovi stili di avvicinamento all’età adulta
La messa in discussione dello schema tradizionale di raggiungimento dei ruoli adulti attraverso un percorso lineare e a tappe determina la creazione di sette nuovi tipi di condizioni rispetto alla transizione in cui i giovani possono trovarsi, a seconda di variabili quali la classe sociale d’appartenenza, il livello di istruzione e il territorio di appartenenza. Tra le nuove figure emergenti troviamo gli studenti conviventi con i genitori; i giovani che hanno terminato la scuola ma non hanno un lavoro stabili e perciò convivono con i genitori; i giovani lavoratori che continuano a vivere con i genitori, sperimentando un’indipendenza extradomestica simultaneamente alla dipendenza domestica; giovani sposati e con figli che continuano a vivere nella famiglia d’origine, dove possono tornare dopo l’eventuale separazione. Tra le rilevazioni IARD del 1996 e quella del 2000, si evidenzia l’aumento esponenziale dei giovani single, ovvero lavoratori indipendenti economicamente, che hanno superato la soglia di uscita dalla famiglia d’origine, ma che non hanno creato una nuova famiglia. Dall’altro lato, sono presenti giovani italiani che, pur non lavorando, hanno scelto di anticipare la transizione rendendosi autonomi dal punto abitativo, formando una nuova famiglia. La condizione più tradizionale del giovane lavoratore totalmente indipendente dai genitori che crea una famiglia si trova nel 45,8% della fascia dei 30-34enni, confermando la tendenza tipicamente italiana di realizzare il definitivo passaggio al mondo adulto dopo i trent’anni.  
Oltre al radicamento del modello di famiglia lunga centrato sul protrarsi della permanenza nella famiglia d’origine fino al matrimonio, l’analisi dei dati presentati nel Sesto rapporto IARD (2007, p. 162) mostra l’emergere di un modello innovativo di passaggio all’età adulta, rappresentato dall’uscita di casa senza che si sia formata una propria famiglia. Mentre il modello tradizionale permane tra i giovani appartenenti a classi sociali più modeste, che vivono in piccoli centri, con una bassa scolarizzazione e un precoce accesso al mercato del lavoro, il nuovo modello si diffonde tra i giovani di collocazione sociale medio-alta, che vivono nei contesti urbani delle zone centro-settentrionali. Il modello di famiglia lunga sembra configurarsi come un modello di transizione da quello tradizionale a quello più innovativo. Perciò la tendenza generale mostra un diffondersi del modello tradizionale nei ceti sociali e contesti territoriali dove prima era poco presente e un suo ridimensionamento nei ceti sociali più elevati e nei contesti coinvolti da processi di modernizzazione in cui si era diffuso precedentemente. 
Questa tendenza si accompagna a cambiamenti strutturali che hanno come oggetto le famiglie, che sono al centro di due processi. Da un lato sono soggetti alla pluralizzazione, con la diffusione di nuove forme familiari in seguito all’instabilità coniugale che genera sempre più famiglie monogenitoriali o con la presenza di più genitori sociali; dall’altro vivono un assottigliamento a seguito della diminuzione della natalità che comporta una diminuzione del numero dei componenti del nucleo familiare. A differenza di quanto accadeva in passato, la permanenza in famiglia è scelta piuttosto che subita, soprattutto a seguito del cambiamento delle condizioni di convivenza con i genitori. Il vivere con i genitori non è più sinonimo di vincoli, limitazioni alla libertà personale e ostacolo alla vita sociale, bensì fonte di vantaggi. Continuare a vivere con i genitori anche quando si dispone di un’entrata economica sufficiente da poter permettere l’uscita dal nucleo familiare d’origine, infatti, presenta numerosi lati positivi se confrontati con gli oneri legati all’assunzione delle responsabilità tipiche della condizione adulta.
La maggior parte dei giovani si dichiara contento della vita in famiglia. Infatti, solo l’8,4% dei giovani afferma di sentirsi abbastanza scontento e un esiguo 1,8% del tutto scontento, in un contesto in cui un maggior livello di scontento è fortemente correlato all’aumento del livello di collaborazione richiesto dal nucleo domestico e dei vincoli posti alle libertà personali. Nonostante si notino alcune differenze a livello territoriale e di classe sociale, con la presenza di una maggiore apertura alla libertà nelle famiglie di ceto elevato delle grandi città nelle regioni centro-settentrionali, a fronte di una maggiore presenza di costrizioni e vincoli nei piccoli centri e nel sud Italia, dove la divisione dei compiti familiari è ancora fortemente strutturata secondo logiche di genere, ciò che emerge è l’affermazione di un nuovo modello nei rapporti tra genitori e figli che permangono all’interno della famiglia d’origine. La tendenza generale registrata mostra, seppur con differenze di genere, un minore coinvolgimento dei giovani nell’organizzazione domestica quotidiana, ad eccezione della richiesta di tenere in ordine la propria camera che risponde, tra l’altro, ad uno spazio personale e di costruzione della propria identità. Un altro contributo fortemente limitato è quello economico, poiché ai giovani viene sempre meno richiesto di contribuire al bilancio familiare con il proprio stipendio. La diffusione di nuovi modelli di coabitazione è dunque alla base della soddisfazione dichiarata dai giovani per la vita in famiglia, caratterizzato da un rapporto non più gerarchico e autoritario, ma basato sul dialogo e la comprensione, pur mantenendo modelli di accudimento elevati. 
Analizzando le percezioni dei giovani, emerge come la presenza di un reddito sufficiente sia una condizione fondamentale per compiere le cinque grandi transizioni. Il principale ostacolo all’indipendenza, infatti, è il fattore economico, oltre all’inerzia inerzia nella ricerca della sistemazione, all’elevata selettività nella scelta e ad un’idea di autonomia abitativa legata a progetti di convivenza. I giovani, forti del sostegno della famiglia che consente di scegliere se compiere o rimandare la transizione, tendono a sottolineare i vantaggi del prolungare la vita in famiglia poiché rappresenta un vantaggio economico, consentendo una maggiore possibilità di consumo e più tempo libero a disposizione. Tuttavia, raggiungere l’indipendenza garantisce un miglioramento nella percezione della qualità della propria vita, oltre che un più alto livello di soddisfazione. In questo quadro, i giovani italiani si configurano sempre più come autonomamente dipendenti, per cui “si percepiscono e rappresentano come autonomi, in quanto in grado e nella possibilità di decidere per sé, definendo i propri percorsi formativi e lavorativi, combinando più risorse, gestendo la loro quotidianità, in definitiva elaborando un proprio sistema di preferenze, pur dovendo dipendere economicamente dai genitori” (Bertolini 2008, p. 97).  


## CONCLUSIONI 

L’obiettivo al centro del presente elaborato è rappresentato dall’analisi degli effetti che vivere un periodo di mobilità all’estero può avere all’interno del peculiare modello di transizione all’età adulta. Considerando le particolarità della condizione giovanile in Italia, caratterizzata da un forte familismo che si traduce nella tendenza alla famiglia lunga, per cui una quota sempre più elevata di giovani permane nella famiglia d’origine per periodi di tempo sempre più lunghi, ci si è posti l’obiettivo di indagare la possibile funzione adultizzante dell’esperienza Erasmus. Tuttavia, sarebbe poco corretto considerare questo come l’unico obiettivo. L’intento della ricerca empirica che è stata condotta e i relativi risultati che ne sono derivati, infatti, non sono esclusivamente funzionali a verificare l’ipotesi di ricerca. 
Il secondo intento è rappresentato dal tentativo di utilizzare i risultati con lo scopo di smantellare alcuni preconcetti ampiamente diffusi nell’opinione pubblica. I dati raccolti all’interno delle rilevazioni EUROSTAT del 2016 mostrano come la percentuale di giovani italiani, compresi nella fascia d’età 18 – 34 anni, che vivono con i genitori sia maggiore rispetto alla media europea di oltre 15 punti percentuali, oltre a registrare un alto livello di disoccupazione, conseguenza di un basso tasso di partecipazione giovanile al mercato del lavoro. La lettura di questi dati ha condotto a fornire un preciso quadro dei giovani italiani, che sono stati definiti “bamboccioni” dall’ex Ministro dell’Economia e delle Finanze Padoa-Schioppa e additati come “mammoni” dall’ex Ministra dell’Interno Annamaria Cancellieri. Queste descrizioni, però, non sono elaborate sulla base di un attento studio del quadro completo della situazione giovanile in Italia. L’intento dell’analisi del peculiare caso italiano che è stata condotta nel Capitolo 1 è stato quello di fornire una visione completa dei fattori che agiscono come determinanti nel rendere difficile il processo di transizione all’età adulta, cercando di rifiutare qualsiasi interpretazione semplicistica del ritardo che si registra nel nostro Paesi rispetto alle nazioni nordeuropee. 
La narrazione dei giovani italiani come “bamboccioni” e “mammoni”, inoltre, può essere confutata dalla discussione dei risultati delle interviste condotte con gli studenti, che esprimono un forte desiderio di autonomia, in primis abitativa. La maggior parte degli studenti, infatti, non accetta di continuare la convivenza con i genitori per una questione di comodità o pigrizia. Ciò che emerge dalle interviste, infatti, è un profondo bisogno dei propri spazi e dei propri tempi, il desiderio di gestire in prima persona la propria vita. Il percorso verso l’acquisizione dell’autonomia, tanto abitativa quanto psicologica, però, è frenata da ostacoli di tipo economico. Questa visione è sostenuta dal significato che assume e dalle aspettative che si riflettono sull’esperienza Erasmus. 
In un contesto di scarso sostegno istituzionale, in cui la posticipazione dell’accesso ai ruoli adulti e la precarizzazione del mercato del lavoro non sono state compensate da politiche pubbliche in grado di garantire sicurezza e autonomia economica dai genitori, e l’assenza di un mercato degli affitti esteso e flessibile in grado di favorire un’uscita precoce, l’Erasmus si configura come lo strumento ideale per intraprendere un percorso di indipendenza. 
Per molti studenti italiani, infatti, i fondi dell’Unione Europea ricevuti attraverso l’erogazione della borsa di studio rappresentano l’aiuto necessario che consente loro di sperimentare per la prima volta un periodo di vita autonoma all’estero. 
L’Erasmus, dunque, può considerarsi come un’esperienza potenzialmente adultizzante all’interno di un contesto italiano che offre ben poche alternative e sostegni per favorire il processo di transizione ai ruoli adulti. Questa affermazione è ritenuta valida sulla base dei racconti degli erasmiani intervistati e del paradigma sociologico mainstream secondo cui la transizione all’età adulta è composta dal superamento di cinque soglie che, pur essendo sempre più dilatate, interscambiabili e reversibili, sono ancora ritenute uno schema interpretativo valido. Perciò l’Erasmus può essere letto come un’esperienza adultizzante nel momento in cui favorisce non solo l’autonomia abitativa che è una delle tappe tradizionali nel percorso di transizione, ma anche un profondo senso di autonomia e consapevolezza circa le proprie capacità di cavarsela da soli. La consapevolezza di riuscire ad autogestirsi e dunque di poter vivere in maniera autonoma senza il sostegno della rete familiare è sviluppata da due fattori. Il primo è il trovarsi a vivere all’estero lontani dalla propria famiglia, per cui l’unica alternativa possibile è farsi carico in prima persona dei problemi. Il secondo fattore, invece, appare come conseguenza del primo, per cui il vivere autonomamente consente di cimentarsi in campi prima sconosciuti, sperimentando una maggiore libertà e svolgendo compiti che erano precedentemente delegati ai genitori. Il fatto di scoprirsi capaci in molti ambiti agisce come fattore determinante nella scelta di mantenere questa indipendenza anche dopo la fine dell’esperienza Erasmus, traducendosi nella spinta necessaria per compiere una transizione completa e diventare definitivamente autonomi dal punto di vista abitativo.   
È possibile individuare anche un secondo risvolto positivo nel vivere un periodo di mobilità all’estero. Le situazioni e le difficoltà che ci si ritrova a fronteggiare durante l’Erasmus, per di più in un Paese diverso e caratterizzato da differenze socio-culturali e linguistiche, permettono di sviluppare una forte autonomia psicologica, che gli intervistati considerano fondamentale nel percorso che li condurrà verso i ruoli adulti. 
Occorre anche evidenziare un potenziale punto critico per cui l’Erasmus potrebbe essere considerato come un’esperienza solo parzialmente adultizzante. Se si considerano le autodefinizioni fornite dagli studenti, infatti, si nota come nessuno si identifica pienamente con i ruoli adulti. La sensazione in seguito all’Erasmus è quella di sentirsi sì più autonomi, ma non adulti. Tuttavia, appare diffusa la consapevolezza di essere in un momento di transizione in cui sì non si è totalmente adulti, ma non ci si riconosce più in una condizione di giovinezza. 
In conclusione, all’interno del peculiare contesto italiano di transizione all’età adulta, l’Erasmus si configura come un’esperienza in grado di offrire gli strumenti economici e psicologici per compiere alcuni passi di questo percorso, permettendo di sperimentare un primo periodo di vita autonoma che in molti casi non si limita ad un preciso periodo di tempo ma si traduce in una condizione stabile di indipendenza. Dunque, pur non consentendo di portare totalmente a termine il percorso di transizione, all’interno del modello italiano l’Erasmus diventa uno strumento fondamentale in assenza di sostegni alternativi. Questa constatazione potrebbe risultare utile se osservata anche da una prospettiva istituzionale. Considerando l’assenza di sostegni economico-istituzionali per favorire un’uscita precoce dalla famiglia d’origine e le potenzialità dell’Erasmus come un efficace strumento che incoraggia la transizione all’età adulta mediante l’acquisizione dell’autonomia abitativa e psicologica potrebbe rappresentare un innovativo punto di partenza per una discussione orientata alla ricerca di una soluzione per fronteggiare la difficile condizione giovanile in Italia e abbandonare definitivamente quelle interpretazioni semplicistiche che li dipingono come mammoni e bamboccioni, ignorando ancora una volta ogni loro richiesta di autonomia. 





## BIBLIOGRAFIA

1. Bertolini S. (a cura di) (2018), Giovani senza futuro? Insicurezza lavorativa e autonomia nell'Italia di oggi, Carocci editore, Roma 
1. Buzzi C., Cavalli A., De Lillo A. (a cura di) (2002), Giovani del nuovo secolo: quinto rapporto IARD sulla condizione giovanile in Italia, Il Mulino, Bologna 
1. Buzzi C., Cavalli A., De Lillo A. (a cura di) (2007), Rapporto giovani: sesta indagine dell’Istituto IARD sulla condizione giovanile in Italia, Il Mulino, Bologna 
1. Corradi S. (2015), Erasmus ed Erasmus Plus. La mobilità internazionale degli studenti universitari, Università Roma Tre, Roma. Disponibile su: https://www.sofiacorradi.eu
1. Garelli F. e Offi M. (1997), Giovani: una vecchia storia?, SEI, Torino 
1. Guizzardi L. (2007), La transizione all’età adulta. Teorie sociologiche a confronto, LED, Milano 
1. Krupnik S. e Krzaklewska E. (2013), “Researching the impact of ERASMUS on European identification: the proposal of a conceptual framework”, in The ERASMUS Phenomenon – Symbol of a New European Generation?, pp. 207-228. Disponibile su: ttps://www.researchgate.net/publication/337768984_Researching_the_impact_of_ERASMUS_on_European_identification_-_the_proposal_of_a_conceptual_framework
1.  Krzaklewska E. (2008), “Why Study Abroad? An Analysis of Erasmus Students’ Motivations”, in Students, Staff and Academic Mobility in Higher Education, Cambridge Scholars Press. Disponibile su: https://www.academia.edu/6873811
1. Krzaklewska E. (2013), “ERASMUS Students between Youth and Adulthood: Analysis of the Biographical Experience”, in Feyen B. e Krzaklewska E., a cura di, The ERASMUS Phenomenon – Symbol of a New European Generation?, Peter Lang AG, Berna. Disponibile su: ttps://www.academia.edu/6873851
1. Lupton, D. (1999), L'anima nel piatto, il Mulino, Bologna (I ed. 1996)
1. Nørgaard T. (2014), “Liberal Education in the Erasmus Programme”, in B. Streitwieser, a cura di, Internationalisation of Higher Education and Global Mobility, Symposium Book, da pag. 99 a pag. 115 


